### ISSUE TITLE
Ground truth bayer data size is 640x640x3?

### ISSUE THREAD

**Issue by sky135410** [goutamgmb/deep-burst-sr#12]
When I load canon bayer data(im_raw.png), it has size 640x640x3
If I want to transfer it to bayer size (EX: NxNx1), should I just sample the data point in 640x640x3?

**Comment by goutamgmb** [comment]
Hi,

I am not sure exactly what you want to do. If you want to perform the mosaicking to get RAW bayer data from the RGB image, yes you can sample the appropriate data points from the RGB image

**Comment by sky135410** [comment]
OK, thanks for your answer.
