### ISSUE TITLE
How to crop raw images in training dataset?

### ISSUE THREAD

**Issue by doooooithey** [goutamgmb/deep-burst-sr#14]
Hi, @goutamgmb ! Thanks a lot for your wonderful work in DBSR. In the BurstSR Dataset, you mention that the cropped images in training dataset are generated from the burst images. I guess it means that you use the original raw image to crop into the resized training raw images. So my question is, **how to crop the RAW image**? 

Again, thanks a lot for your excellent job! Look forward to your reply :)

**Comment by goutamgmb** [comment]
Hi,

We convert the RAW images to 4 channel format. Next we extract crops from the RAW images (all images in the burst) as well as corresponding DSLR RGB image in a sliding window manner.
