### ISSUE TITLE
How to avoid checkerboard artifacts?

### ISSUE THREAD

**Issue by SolskyPan** [goutamgmb/deep-burst-sr#16]
Hi, thanks for the excellent work. When I tried to test your pretrained model on my captured RAW bursts, I prepared my testing datasets as your evaluation datasets —— RAW bursts captured from Samsung Galaxy S8, 4 channels 'png' format and uint16 type. However, I found that there exists checkerboard artifacts in the output super resolution image. How to avoid these checkerboard artifacts?

The input sample and the output image are shown in the https://drive.google.com/drive/folders/15ya_CuvVZ65gjBwXqfjTd1pgqi3da8cO?usp=sharing

**Comment by SolskyPan** [comment]
All RAW bursts are shown here
https://drive.google.com/drive/folders/15ya_CuvVZ65gjBwXqfjTd1pgqi3da8cO

**Comment by goutamgmb** [comment]
Hi,

The results look quite strange. I would guess that the issue is in the input format of the data. I would suggest double checking that. We expect the input to have 4 channels (R G G B).
