### ISSUE TITLE
Example on how to convert {sRGB} to {RAW BURST} please

### ISSUE THREAD

**Issue by orilifs** [goutamgmb/deep-burst-sr#21]
Hello

An example on what's the proper way to create a script that takes as input: str:'path_to_img.jpg'
and returns as output: folder with dng files

thanks

**Comment by goutamgmb** [comment]
Hi,

I have added a script [generate_synthetic_dataset.py](https://github.com/goutamgmb/deep-burst-sr/blob/master/util_scripts/generate_synthetic_dataset.py) which takes as input path to a folder containing sRGB images and generates raw bursts. The burst images are saved as 16 bit pngs, along with some meta info. You can refer to [this](https://github.com/goutamgmb/deep-burst-sr/blob/master/dataset/synthetic_burst_val_set.py) dataset class for an example on how to load the generated bursts.

Regards
