### ISSUE TITLE
ModuleNotFoundError: No module named 'correlation'

### ISSUE THREAD

**Issue by yangzheng-yz** [goutamgmb/deep-burst-sr#25]

**Comment by jakubsadel** [comment]
how did you solve this problem @yangzheng-yz ??

**Comment by June-phy** [comment]
I have the some problem. How do you solve this problem?

**Comment by TTiinnaa** [comment]
Hey I got the same problem how did you fix it buddy @yangzheng-yz

**Comment by Sherman86** [comment]
Solved. Incompat of cupy.
Refer to the web:
https://docs.cupy.dev/en/latest/install.html
