### ISSUE TITLE
Can't download the PWC-Net

### ISSUE THREAD

**Issue by yjsunnn** [goutamgmb/deep-burst-sr#5]
Hi @goutamgmb I can't download the pretrained pwc-net using the install.sh and the 'gdown' command, and I also can't open the google drive link you provide. Could you please give some advice?

**Comment by susan-sun1999** [comment]
Absolutely. I'm not sure whether it's my own issue or not. But I really tried a lot of times.
![image](https://user-images.githubusercontent.com/54736521/136938963-bcbef62c-16bd-47d7-a301-0dce68ecad78.png)

**Comment by zhihengnono** [comment]
Hi @goutamgmb could you please provide the google drive link for the model dbsr_burstsr_default.pth as well? Thanks~
